version: '2'
services:
  jhipsternewapplication-app:
    image: jhipsternewapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsternewapplication-postgresql:5432/jhipsterNewApplication
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  jhipsternewapplication-postgresql:
    extends:
      file: postgresql.yml
      service: jhipsternewapplication-postgresql
